//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Be.HexEditor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Be.HexEditor.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Byte {0} 的本地化字符串。
        /// </summary>
        internal static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file does not exist! 的本地化字符串。
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find reached end of file! 的本地化字符串。
        /// </summary>
        internal static string FindOperationEndOfFile {
            get {
                return ResourceManager.GetString("FindOperationEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italian 的本地化字符串。
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No byte is selected 的本地化字符串。
        /// </summary>
        internal static string NoByteSelected {
            get {
                return ResourceManager.GetString("NoByteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File is locked by another process and cannot be opened! 的本地化字符串。
        /// </summary>
        internal static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file is locked. Do you want to open it in read-only mode? 的本地化字符串。
        /// </summary>
        internal static string OpenReadonly {
            get {
                return ResourceManager.GetString("OpenReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program restart required for settings to take affect! 的本地化字符串。
        /// </summary>
        internal static string ProgramRestartSettings {
            get {
                return ResourceManager.GetString("ProgramRestartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [read-only] 的本地化字符串。
        /// </summary>
        internal static string Readonly {
            get {
                return ResourceManager.GetString("Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Russian 的本地化字符串。
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save changes? 的本地化字符串。
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        internal static string SimplifiedChinese {
            get {
                return ResourceManager.GetString("SimplifiedChinese", resourceCulture);
            }
        }
    }
}
